### ISSUE TITLE
Predicting the model with rectangular input

### ISSUE THREAD

**Issue by alwc** [cherubicXN/hawp#7]
Hi @cherubicXN 

I'm trying to train the wireframe dataset with rectangular input shape, i.e.  in `hawp.yaml`, I set 

```
DATASETS:
  IMAGE:
    HEIGHT: 576
    WIDTH: 448
  TARGET:
    HEIGHT: 144
    WIDTH: 112
```

but it doesn't seem to be trainable at all. The highest sAP10.0 I'm getting is around ~7. Do you know what shall I be aware of if I want to train my model with rectangular input? Thanks!
